/* Generated By:JavaCC: Do not edit this line. Prog3TreeConstants.java Version 7.0.5 */
public interface Prog3TreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTAPPL = 2;
  public int JJTLAMBDA = 3;
  public int JJTVAR = 4;
  public int JJTCONSTANT = 5;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Appl",
    "Lambda",
    "var",
    "constant",
  };
}
/* JavaCC - OriginalChecksum=69ae79d61a80ddc0d6d71939d2f39d86 (do not edit this line) */
